[package]
name = "zmix"
version = "0.1.0"
authors = ["Michael Lodder <redmike7@gmail.com>"]
license = "Apache-2.0"

[lib]
name = "zmix"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
amcl = { path = "./amcl" }
serde_json = "1.0.26"
rand = "0.5.3"
